name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies
        run: npm install

      - name: Run tests (optional)
        run: npm test  # This step can be skipped if you don't have tests

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}  # Your EC2 instance IP or hostname
          USER: ${{ secrets.EC2_USER }}  # Your SSH user
          KEY: ${{ secrets.EC2_SSH_KEY }}  # Your private SSH key
        run: |
          # Copy files to EC2 instance
          echo "$KEY" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem -r ./* $USER@$HOST:/path/to/your/app/
          
          # SSH into EC2 and restart the server
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << 'EOF'
            cd /path/to/your/app/
            npm install   # Install any new dependencies
            npm start     # Or however you start your server
          EOF
