name: Deploy to AWS on Pull Request

on:
  push:
    branches:
      - main  # You can adjust this to your specific branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-109-155-26.ap-south-1.compute.amazonaws.com << 'EOF'
          cd meldlens-mvp-server  # Replace with the actual project directory
          git pull origin main      # Pull the latest changes from the GitHub repo
          npm install               # Install dependencies if necessary
          pm2 restart all           # Restart the Node.js app using PM2
        EOF
